USE [CLARITY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DECLARE @startdate DATETIME = NULL, 
	@enddate DATETIME = NULL

SET @startdate = '7/1/2022 00:00 AM'
SET @enddate = '10/31/2022 11:59 PM'

	SET NOCOUNT ON;

	IF @startdate IS NULL
    AND @enddate IS NULL
    BEGIN
	--Set Parameter Values
	   
	    SET @enddate = CAST(CAST(GETDATE() AS DATE) AS DATETIME) 
		SET @startdate = DATEADD(dd,-1,@enddate)


	END;

DECLARE @locstartdate DATETIME,
        @locenddate DATETIME
SET @locstartdate = @startdate
SET @locenddate   = @enddate

SELECT txf.[COMM_ID]
      ,last_mod.STATUS_UPDATE_UTC_DTTM
	  ,CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(STATUS_UPDATE_UTC_DTTM) AS LOCAL_STATUS_UPDATE_UTC_DTTM
      ,txf.[TARGET_DEST_COMM_ID]
      ,[TARGET_DEST_LOC_ID]
      ,[FINANCIAL_APPROVAL_DTTM]
      ,[MEDICAL_APPROVAL_DTTM]
      ,[SOCIAL_APPROVAL_DTTM]
      ,[TRANSFER_ACCEPT_UTC_DTTM]
      ,[TRANSFER_START_UTC_DTTM]
      ,[TRANSFER_RESOLUTION_UTC_DTTM]
      ,[TRANSFER_ACCEPT_PROV_ID]
      ,[FIRST_PROV_CONTACT_UTC_DTTM]
      ,[ACC_PROV_CONTACT_UTC_DTTM]
      ,[TRANSFER_BED_ASGN_DTTM]
      ,[TRANSFER_BED_READY_DTTM]
      ,[TRANSFER_LENGTH_OF_STAY_DAYS]
      ,[TRANSFER_INPATIENT_DAYS]
      ,[BED_READY_APPROVAL_DTTM]
      ,[TRANSFER_START_DTTM]
      ,[REFERRING_ZONE_C]
      ,[REQUESTED_ZONE_C]
      ,[DEST_ZONE_C]
      ,[INTAKE_PAT_ENC_CSN_ID]
      ,[RESULTANT_PAT_ENC_CSN_ID]
      ,txf.[REFERRING_LOC_ID]
      ,[TRANSFER_ADMITTING_PROV_ID]
      ,[FIRST_CONTACTED_PROV_ID]
      ,txf.[TC_PRIORITY_C]
      ,[REQUESTED_DEST_COMM_ID]
      ,txf.[REQUESTED_DEST_LOC_ID]
      ,[REQUESTED_DEST_DECLINE_CAT_C]
      ,[REQUESTED_DEST_DECLINE_RSN_C]
      ,[REFERRING_LOC_IS_EXTERNAL_YN]
      ,[TARGET_DEST_IS_EXTERNAL_YN]
      ,[REQUESTED_DEST_IS_EXTERNAL_YN]
      ,[ACC_PROV_FST_DECISION_UTC_DTTM]
      ,[ADMSN_PEND_ID]
      ,[ADMSN_EVENT_ID]
      ,[ADMSN_DEPARTMENT_ID]
      ,[ADMSN_ROOM_ID]
      ,[ADMSN_BED_ID]
      ,[TRANSFER_ORDER_ID]
      ,[RESULTANT_HSP_ACCOUNT_ID]
      ,[RESULTANT_PRIM_COVERAGE_ID]
      ,[RESULTANT_PRIM_PAYOR_ID]
      ,[RESULTANT_PRIM_FIN_CLASS_C]
      ,[ADMITTING_PROV_UTC_DTTM]
      ,[USE_ACCEPT_STATUS_YN]
	  ,loc1.LOC_NAME AS REFERRING_LOC_NAME
	  ,loc2.LOC_NAME AS TARGET_DEST_LOC_NAME
	  ,loc3.LOC_NAME AS REQUESTED_DEST_LOC_NAME
  FROM [CLARITY].[dbo].[V_ADT_TRANSFER_CENTER] txf
  INNER JOIN CLARITY.dbo.CUST_SERVICE_TRANSFER txfsvc
  ON txfsvc.COMM_ID = txf.COMM_ID
  LEFT OUTER JOIN CLARITY.dbo.CLARITY_LOC loc1
  ON loc1.LOC_ID = txf.REFERRING_LOC_ID
  LEFT OUTER JOIN CLARITY.dbo.CLARITY_LOC loc2
  ON loc2.LOC_ID = txf.TARGET_DEST_LOC_ID
  LEFT OUTER JOIN CLARITY.dbo.CLARITY_LOC loc3
  ON loc3.LOC_ID = txf.REQUESTED_DEST_LOC_ID
LEFT OUTER JOIN (
					SELECT hx.COMM_ID
							,hx.REQUEST_STATUS_C
							,sts.NAME 'RequestStatus'
							,hx.STATUS_UPDATE_UTC_DTTM
							,hx.STATUS_UPDATE_USER_ID
							,emp.USER_ID
							,emp.SYSTEM_LOGIN
							,ROW_NUMBER() OVER(PARTITION BY hx.COMM_ID ORDER BY hx.STATUS_UPDATE_UTC_DTTM DESC) 'RNo'
					FROM CLARITY.dbo.TC_REQUEST_STATUS_HX hx
					LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp			ON hx.STATUS_UPDATE_USER_ID=emp.USER_ID
					LEFT OUTER JOIN CLARITY.dbo.ZC_TC_REQUEST_STATUS sts	ON hx.REQUEST_STATUS_C=sts.TC_REQUEST_STATUS_C
					WHERE 1=1
					--AND CLARITY_App.dbo.udf_UTC_to_DST(hx.STATUS_UPDATE_UTC_DTTM) >= @StartDate
					AND CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(hx.STATUS_UPDATE_UTC_DTTM) >= @StartDate
					--AND CLARITY_App.dbo.udf_UTC_to_DST(hx.STATUS_UPDATE_UTC_DTTM) <  @EndDate
					AND CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(hx.STATUS_UPDATE_UTC_DTTM) <  @EndDate
				) last_mod											ON last_mod.COMM_ID = txf.COMM_ID
																		AND last_mod.RNo='1'

WHERE 1=1

----	AND idx.IDENTITY_TYPE_ID='14'
----	AND inttxf.ATCHMENT_TYPE_C='22' --Transfer Center Intake/ 21	Transfer Center Destination
----	AND dsttxf.ATCHMENT_TYPE_C='18' -- Admission --'21' --Transfer Center Destination
----	AND pnd.PEND_EVENT_TYPE_C='1' --Admission
----	AND hsp.PREADM_UNDO_RSN_C IS NULL --pre-admission not cancelled
--  AND (serid.IDENTITY_TYPE_ID='100001' OR serid.IDENTITY_ID IS NULL )

	AND CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(last_mod.STATUS_UPDATE_UTC_DTTM) >= @locstartdate
	AND CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(last_mod.STATUS_UPDATE_UTC_DTTM) <  @locenddate

  ORDER BY txf.COMM_ID, last_mod.STATUS_UPDATE_UTC_DTTM
GO