USE CLARITY

SELECT t.REPORT_ID Template_id, t.REPORT_NAME Template_Name,  dbo.ZC_REPORT_TYPE_HGR.NAME RPT_Type,

        dbo.ZC_REPORT_FREQ.NAME FREQ, t2.CRYSTAL_FILENAME, t2.ENTERPRISE_FOLDER,

              dbo.ZC_OUTPUT_FORMAT.NAME Fmt,

               rpt.REPORT_ID rpt_id,
			   
			   --rpt.X_ASSOC_REPORT_ID X_Rpt_id,
			   
			   rpt.REPORT_NAME Rpt_name, rpt.REPORT_TYPE Rpt_group,

               hrx.REPORT_INFO_ID HRX_ID, hrx.REPORT_INFO_NAME, zp.NAME Priv_Public,

               hrx.OWNED_BY_USER_ID User_id, emp.NAME Created_by, hrx.LAST_MOD_BY_USER_ID Mod_user, mod.NAME Modified_by,

               sub.USER_ID Published_id, sub.NAME Published,

              t.STATUS_C, t.REPORT_TYPE_C

 

FROM dbo.TEMPLATE_INFO t

LEFT JOIN dbo.TEMPLATE_INFO_2 t2 ON t.REPORT_ID = t2.REPORT_ID

--LEFT JOIN dbo.TEMPLATE_INFONAME tn ON t2.REPORT_ID = tn.REPORT_ID

--LEFT JOIN dbo.CLARITY_RPT rpt ON t2.REPORT_ID = rpt.X_ASSOC_REPORT_ID

LEFT JOIN dbo.CLARITY_RPT rpt ON t2.REPORT_ID = rpt.REPORT_ID

LEFT JOIN dbo.REPORT_INFO hrx ON t.REPORT_ID = hrx.REPORT_ID

LEFT JOIN dbo.CLARITY_EMP emp ON hrx.OWNED_BY_USER_ID = emp.USER_ID

LEFT JOIN dbo.CLARITY_EMP mod ON hrx.LAST_MOD_BY_USER_ID = mod.USER_ID

LEFT JOIN dbo.SUBSCRIBED_REPORTS publ ON hrx.REPORT_INFO_ID = publ.SUBSCRIBED_REPT_ID

LEFT JOIN dbo.CLARITY_EMP sub ON publ.USER_NUMBER_ID = sub.USER_ID

LEFT JOIN dbo.ZC_REPORT_TYPE_HGR ON t.REPORT_TYPE_HGR_C = dbo.ZC_REPORT_TYPE_HGR.REPORT_TYPE_HGR_C

LEFT JOIN dbo.ZC_REPORT_FREQ ON t.REPORT_FREQ_C = dbo.ZC_REPORT_FREQ.REPORT_FREQ_C

LEFT JOIN dbo.ZC_OUTPUT_FORMAT ON t2.OUTPUT_FORMAT_C = dbo.ZC_OUTPUT_FORMAT.OUTPUT_FORMAT_C

LEFT JOIN dbo.ZC_RW_PRIV_OR_PUB zp ON hrx.PRIVATE_OR_PUBLIC_C = zp.PRIVATE_OR_PUBL_C

 --WHERE t.REPORT_TYPE_HGR_C = '3'

 -- AND t.REPORT_ID > '99999'

 -- AND sub.NAME LIKE '%BURGAN%'

 WHERE sub.NAME LIKE '%BURGAN%'

ORDER BY  t.REPORT_NAME, t.REPORT_ID, hrx.REPORT_ID