SELECT ri.REPORT_INFO_ID, ri.REPORT_INFO_NAME, ri.RPT_TYPE_C, ri.PRIVATE_OR_PUBLIC_C, ri.TEMP_REPORT_C
    , ri.RECORD_TYPE_C, ri.INST_OF_CREATION_DTTM, ri.INST_OF_LAST_MOD_DTTM
	, ti.REPORT_ID, ti.REPORT_NAME, ti.SRC_TEMPL_ID, ti.REPORT_TYPE_C
FROM REPORT_INFO ri
	LEFT JOIN TEMPLATE_INFO	ti ON ri.REPORT_ID = ti.REPORT_ID