USE CLARITY
GO

/*SELECT --TOP 50 
				rhx.REG_HX_OPEN_PAT_CSN 'CSN'
				,CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(rhx.REG_HX_INST_UTC_DTTM) 'DTTM'
				,rhx.REG_HX_USER_ID 'USER_ID'
				,ROW_NUMBER() OVER (PARTITION BY rhx.REG_HX_OPEN_PAT_CSN ORDER BY CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(rhx.REG_HX_INST_UTC_DTTM)) 'RNo'
				,rhx.REG_HX_EVENT_C
				,zrhx.NAME AS REG_HX_EVENT_NAME
				,emp.NAME
				FROM CLARITY.dbo.REG_HX Rhx
				LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp
				ON emp.USER_ID = rhx.REG_HX_USER_ID
				LEFT OUTER JOIN CLARITY.dbo.ZC_REG_HX_EVENT_TYPE zrhx
				ON zrhx.REG_HX_EVENT_C = Rhx.REG_HX_EVENT_C
				WHERE Rhx.REG_HX_OPEN_PAT_CSN = 200027430052
				ORDER BY Rhx.REG_HX_OPEN_PAT_CSN, RNo*/

--SELECT  --TOP 10
SELECT  DISTINCT
	--pnd.PEND_ID
	 hsp.CONTACT_DATE
--	,hsp.PAT_ID
--	,ISNULL(HSP.HOSP_ADMSN_TIME,hsp.EXP_ADMISSION_TIME) 'HOSP_ADMSN_TIME'
--	,ENC.COVERAGE_ID
--	,zcrdc.NAME		'Pend_Record_Type'
	,idx.IDENTITY_ID	'MRN'
	 --idx.IDENTITY_ID	'MRN'
	,hsp.PAT_ENC_CSN_ID
	,hsp.HSP_ACCOUNT_ID

	,ISNULL(HSP.HOSP_ADMSN_TIME,hsp.EXP_ADMISSION_TIME) 'HOSP_ADMSN_TIME'
	
--Scheduling
    ,hx.UPDATE_TIME			'PRE_ADMISSION_CREATED'
    ,hx.UPDATE_USER_ID		'PRE_ADMISSION_CREATED_USER_ID'
	,hx.USER_NAME 'PRE_ADMISSION_CREATED_USER'
	-- 20210405 edit
	--,pndcrtd.UPDATE_INST_LOCAL_DTTM  'PRE-ADMISSION CREATED_DTTM'
	--,pndcrtd.UPDATE_USER_ID			 'PRE-ADMISSION CREATED_USER_ID'
	,scdemp.SYSTEM_LOGIN 'SCHEDULING_USER_LOGIN'
	,scdemp.USER_NAME 'SCHEDULING_USER'
	,scdemp.DEFAULT_USER_ROLE 'SCHEDULING_USER_ROLE'
	,scdemp.TEMPLATE_NAME 'SCHEDULING_TEMPLATE_NAME'

--Registration	   
	,reg.USER_ID						'REGISTRATION_STARTED_USER_ID'	   
	,reg.NAME						'REGISTRATION_STARTED_USER'
	,regemp.USER_ID 'REGISTRATION_USER_ID'
	,regemp.USER_NAME 'REGISTRATION_USER'
	,regemp.SYSTEM_LOGIN 'REGISTRATION_USER_LOGIN'
	,regemp.DEFAULT_USER_ROLE 'REGISTRATION_USER_ROLE'
	,regemp.TEMPLATE_NAME 'REGISTRATION_TEMPLATE_NAME'
	,reg.DTTM									'REG_START_TIME' --UTC TIME NEED TO CONVERT
	,regend.DTTM								'REG_END_TIME'


--Patient Verification
/*	,ptvrx.LAST_VERIF_USER_ID			'PATIENT VERIFICATION USER'
	,ptvrxemp.SYSTEM_LOGIN
	,ptvrxemp.DEFAULT_USER_ROLE
	,ptvrxemp.TEMPLATE_NAME
	,ptvrx.LAST_STAT_CHNG_DTTM			'PATIENT VERIFICATION DTTM'   --REGISTRATION COMPLETE TIME
*/
--coverage Verification	
    ,cvgvrx.LAST_VERIF_USER_ID			'BENEFIT_VERIFIED_USER_ID'
	,cvgvrx.NAME 'BENEFIT_VERIFIED_USER'
	,cvgvrxemp.SYSTEM_LOGIN 'BENEFIT_VERIFIED_USER_LOGIN'
	,cvgvrxemp.DEFAULT_USER_ROLE 'BENEFIT_VERIFIED_USER_ROLE'
	,cvgvrxemp.TEMPLATE_NAME 'BENEFIT_VERIFIED_TEMPLATE_NAME'
	,cvgvrx.LAST_STAT_CHNG_DTTM			'BENEFIT_VERIFIED_DATE'

	--,cvgrte.RTE_TRIGGER_USER_ID				'BENEFIT_VERIFIED_USER_ID'
	--,cvgrte.NAME 'BENEFIT_VERIFIED_USER'
	--,cvgvrxemp.SYSTEM_LOGIN 'BENEFIT_VERIFIED_USER_LOGIN'
	--,cvgvrxemp.DEFAULT_USER_ROLE 'BENEFIT_VERIFIED_USER_ROLE'
	--,cvgvrxemp.TEMPLATE_NAME 'BENEFIT_VERIFIED_TEMPLATE_NAME'
	--,cvgrte.SENT_TRUE_INST_DTTM				'BENEFIT_VERIFIED_DATE'

--HAR Verification	
	,harvrx.LAST_VERIF_USER_ID			'HAR_VERIFIED_USER_ID'
	,harvrx.NAME 'HAR_VERIFIED_USER'
	,harvrxemp.SYSTEM_LOGIN 'HAR_VERIFIED_USER_LOGIN'
	,harvrxemp.DEFAULT_USER_ROLE 'HAR_VERIFIED_USER _ROLE'
	,harvrxemp.TEMPLATE_NAME 'HAR_VERIFIED_TEMPLATE_NAME'
	,harvrx.LAST_STAT_CHNG_DTTM			'HAR_VERIFIED_DATE'

--Admission	
	,admhx.UPDATE_USER_ID				'ADMISSION_CONFIRMED_USER_ID'
	,admhx.NAME 'ADMISSION_CONFIRMED_USER'
	,admemp.SYSTEM_LOGIN 'ADMISSION_CONFIRMED_USER_LOGIN'
	,admemp.DEFAULT_USER_ROLE 'ADMISSION_CONFIRMED_USER_ROLE'
	,admemp.TEMPLATE_NAME 'ADMISSION_CONFIRMED_TEMPLATE_NAME'
	,admhx.UPDATE_TIME					'ADMISSION_CONFIRMED_DTTM'

--Point of Origin'	
	,hsp.ADMIT_SOURCE_C					
	,admsrc.NAME				'POINT_OF_ORIGIN'

--Planned/Unplanned admission
	,hsp.HOSP_ADMSN_TYPE_C				
	,admtyp.NAME			'ADMISSION_TYPE'

--Service
	,hsp.HOSP_SERV_C				
	,svc.NAME							'SERVICE'

--Unit
	,hsp.DEPARTMENT_ID
	,dep.DEPARTMENT_NAME				'UNIT'

--Accommodation Code
	,hsp.ACCOMMODATION_C
	,acm.NAME							'ACCOMMODATION_CODE'

--Patient Type
	,zcpttyp.NAME						'PATIENT_TYPE'

--Authi/Cert Status
	,rfl.PRE_CERT_STATUS_C
	,certsts.NAME						'AUTHCERT_STATUS'

--Coverage Info	
	,epm.PAYOR_NAME
	,epp.BENEFIT_PLAN_NAME

--MSPQ
	,mspq.MSP_STATUS_C					
	,zcmsp.NAME							'MSPQ_COMPLETION'

--Documents Insurance Waiver	
	,dcswv.DOC_STAT_C					'INSURANCE_WAIVER_STATUS_C'
	,zcwvst.NAME						'INSURANCE_WAIVER_STATUS'
	,dcswv.RECV_BY_USER_ID				'INSURANCE_WAIVER_COLLECTED_USER_ID'
	,dcswv.NAME 'INSURANCE_WAIVER_COLLECTED_USER'
	,dcswv.DOC_RECV_TIME				'INSURANCE_WAIVER_COLLECTED_DTTM'
	
--Documents Medicare Msg
	,dcsmc.DOC_STAT_C					'MEDICARE_MSG_STATUS_C'
	,zcmcst.NAME						'MEDICARE_MSG_STATUS'
	,dcsmc.RECV_BY_USER_ID				'MEDICARE_MSG_COLLECTED_USER ID'
	,dcsmc.NAME 	'MEDICARE_MSG_COLLECTED_USER'
	,dcsmc.DOC_RECV_TIME				'MEDICARE_MSG_COLLECTED_DTTM'

--Documents Admission Notification
	,dcsadm.DOC_STAT_C					'ADMISSION_NOTICE_STATUS_C'
	,zcadmst.NAME						'ADMISSION_NOTICE_STATUS'
	,dcsadm.RECV_BY_USER_ID				'ADMISSION_NOTICE_COLLECTED_USER_ID'
	,dcsadm.NAME 'ADMISSION_NOTICE_COLLECTED_USER'
	,dcsadm.DOC_RECV_TIME				'ADMISSION_NOTICE_COLLECTED_DTTM'

--RTE
	,rte.RTE_RESP_STATUS_C
	,zcrtest.NAME						'RTE_RESPONSE_STATUS'
	,rte.RTE_TRIGGER_USER_ID 'RTE_TRIGGER_USER_ID'
	,rte.NAME 'RTE_TRIGGER_USER'
	,rte.RTE_SENT_TRUE_DTTM

--MyChart
	,myc.MYCHART_STATUS_C
	,zcmyc.NAME							'MYCHART_STATUS'

--Payments
	,enc.COPAY_DUE
	,enc.COPAY_COLLECTED
	,slfpmt.AMOUNT_PAID					'SELF_PAYMENT_AMOUNT'

--Cancellations
	,enc.APPT_CANCEL_DATE
	,enc.APPT_CANC_USER_ID
	,enc.CANCEL_REASON_C
	,cnlrsn.NAME						'CANCEL_REASON'

--WQ EDITS
--	,rl.RULE_NAME

--HB
 --   ,TX.SERVICE_DATE
	--,CAST(TX.TX_AMOUNT AS NUMERIC(18,2)) AS AMOUNT
	--,ISNULL(TX.DEDUCTIBLE_AMOUNT,'0.00') AS DEDUCTIBLE_AMOUNT
	--,ISNULL(TX.COINSURANCE_AMOUNT,'0.00') AS COINSURANCE_AMOUNT
	--,ISNULL(TX.COPAY_AMOUNT,'0.00') AS COPAY_AMOUNT

FROM
(
SELECT sthx.PAT_ENC_CSN_ID
              ,sthx.UPDATE_USER_ID
			  ,sthx.UPDATE_TIME
			  ,sthx.UPDATED_ENC_STAT_C
			  ,sthx.UPDATED_CONF_STAT_C
			  ,emp.NAME 'USER_NAME'
FROM CLARITY.dbo.PAT_ENC_STAT_HX sthx
LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp
ON emp.USER_ID =  sthx.UPDATE_USER_ID
)
hx

--FROM  CLARITY.dbo.PEND_ACTION pnd
--INNER JOIN CLARITY.dbo.PAT_ENC_HSP hsp						ON pnd.PAT_ENC_CSN_ID = hsp.PAT_ENC_CSN_ID
INNER JOIN CLARITY.dbo.PAT_ENC_HSP hsp						ON hx.PAT_ENC_CSN_ID = hsp.PAT_ENC_CSN_ID
INNER JOIN CLARITY.dbo.PAT_ENC enc							ON hsp.PAT_ENC_CSN_ID = enc.PAT_ENC_CSN_ID
INNER JOIN CLARITY.dbo.IDENTITY_ID idx						ON hsp.PAT_ID = idx.PAT_ID

-- 20210405 edit
--INNER JOIN CLARITY.dbo.PAT_ENC_STAT_HX hx					ON hsp.PAT_ID = hx.PAT_ID
--INNER JOIN CLARITY.dbo.PAT_ENC_STAT_HX hx					ON hsp.PAT_ENC_CSN_ID = hx.PAT_ENC_CSN_ID
--INNER JOIN
--(
--SELECT sthx.PAT_ENC_CSN_ID
--             , sthx.UPDATE_TIME
--             , sthx.UPDATE_USER_ID
--			 , emp.NAME AS USER_NAME
--			 , sthx.UPDATED_ENC_STAT_C
--			 , sthx.UPDATED_CONF_STAT_C
--FROM CLARITY.dbo.PAT_ENC_STAT_HX sthx
--LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp
--ON emp.USER_ID = sthx.UPDATE_USER_ID
--) hx 
--ON hsp.PAT_ENC_CSN_ID = hx.PAT_ENC_CSN_ID

-- 20210405 edit
--INNER JOIN (SELECT hx1.*
--			FROM CLARITY.dbo.BED_PLAN_HX hx1
--			LEFT OUTER JOIN (
--								SELECT *
--								FROM CLARITY.dbo.BED_PLAN_HX hx7
--								WHERE 1=1
--								AND hx7.UPDATE_TYPE_C ='7' 
--							)hx7				ON hx1.PEND_ID = hx7.PEND_ID
--			WHERE 1=1
--			AND hx1.UPDATE_TYPE_C ='1' --CREATED
--			AND hx7.PEND_ID IS NULL --NOT CANCELED
--			) pndcrtd										ON pnd.PEND_ID = pndcrtd.PEND_ID  ---SELECT ONLY NOT CANCELLED PEND RECORDS

--INNER JOIN  (SELECT  ROW_NUMBER()OVER(PARTITION BY reg1.REG_CSN_ID ORDER BY reg1.REG_DATETIME ) 'RNo'
--					,reg1.REG_CSN_ID
--					,reg1.USER_ID
--					,reg1.USER_LOGIN_DEP_ID
--					,reg1.ACTIVE_WORKSPACE_SECONDS
--					,emp.NAME
--				FROM CLARITY.dbo.REG_TIMING reg1
--				LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp
--				ON emp.USER_ID = reg1.USER_ID
--				WHERE 1=1
--					AND reg1.SRC_PAT_WORKQUEUE_ID IS NULL --NOT FROM WQ
--			) reg											ON hsp.PAT_ENC_CSN_ID =	reg.REG_CSN_ID AND reg.RNo='1' -- first user to touch registration
							
INNER JOIN  (SELECT --TOP 50 
				rhx.REG_HX_OPEN_PAT_CSN 'CSN'
				,CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(rhx.REG_HX_INST_UTC_DTTM) 'DTTM'
				,rhx.REG_HX_USER_ID 'USER_ID'
				,ROW_NUMBER() OVER (PARTITION BY rhx.REG_HX_OPEN_PAT_CSN ORDER BY rhx.REG_HX_INST_UTC_DTTM) 'RNo'
				,emp.NAME
				FROM CLARITY.dbo.REG_HX Rhx
				LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp
				ON emp.USER_ID = rhx.REG_HX_USER_ID
			) reg											ON hsp.PAT_ENC_CSN_ID =	reg.CSN AND reg.RNo='1' -- first user to touch registration

			INNER JOIN  (SELECT --TOP 50 
				rhx.REG_HX_OPEN_PAT_CSN 'CSN'
				,CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(rhx.REG_HX_INST_UTC_DTTM) 'DTTM'
				,rhx.REG_HX_USER_ID 'USER_ID'
				,ROW_NUMBER() OVER (PARTITION BY rhx.REG_HX_OPEN_PAT_CSN ORDER BY rhx.REG_HX_INST_UTC_DTTM DESC) 'RNo'
				,emp.NAME
				FROM CLARITY.dbo.REG_HX Rhx
				LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp
				ON emp.USER_ID = rhx.REG_HX_USER_ID
			) regend											ON hsp.PAT_ENC_CSN_ID =	regend.CSN AND regend.RNo='1' -- first user to touch registration

LEFT OUTER JOIN CLARITY.dbo.COVERAGE cvg					ON enc.COVERAGE_ID = cvg.COVERAGE_ID

/***PATIENT VERIFICATION RECORD ONLY DISPLAY THE LAST VERIFICATION RECORD**/
--PATIENT VERIFICATION 
/*LEFT OUTER JOIN (
					SELECT  
						vrxpt.VERIF_RECORD_IDNT
						,vrxpt.LAST_STAT_CHNG_DTTM
						,vrxpt.LAST_VERIF_USER_ID
						,vrxpt.VERIF_STATUS_C
						,vrxpt.NEXT_REVIEW_DATE
						,vrxpt.VERIF_CONFRM_ID
						,vrxpt.RECORD_CREATION_DT
					 FROM  CLARITY.dbo.VERIFICATION vrxpt
					 WHERE 1=1
					 AND vrxpt.VERIFICATION_TYPE_C ='1' --PATEINT
					 AND vrxpt.VERIF_STATUS_C IN ('1','12','13','23','26','6','8')
					 AND vrxpt.VERIF_CONFRM_ID <>'100057' --NOT RACE AND ETHNICITY VERIFICATION
					)ptvrx									ON hsp.PAT_ID = ptvrx.VERIF_RECORD_IDNT 
																AND hsp.HOSP_ADMSN_TIME>=ptvrx.LAST_STAT_CHNG_DTTM
																AND hsp.HOSP_ADMSN_TIME<=CAST(ptvrx.NEXT_REVIEW_DATE AS DATE)
*/

/***COVERAGE VERIFICATION RECORD ONLY DISPLAY THE LAST VERIFICATION RECORD**/
--BENEFIT/COVERAGE VERIFICATION 
--LEFT OUTER JOIN (
--					SELECT  
--						vrxcvg.VERIF_RECORD_IDNT
--						,vrxcvg.LAST_STAT_CHNG_DTTM
--						,vrxcvg.LAST_VERIF_USER_ID
--						,vrxcvg.VERIF_STATUS_C
--						,vrxcvg.NEXT_REVIEW_DATE
--						,vrxcvg.VERIF_CONFRM_ID
--						,vrxcvg.RECORD_CREATION_DT
--						,emp.NAME
--					 FROM  CLARITY.dbo.VERIFICATION vrxcvg
--					 LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = vrxcvg.LAST_VERIF_USER_ID
--					 WHERE 1=1
--						 AND vrxcvg.VERIFICATION_TYPE_C ='6' --COVERAGE MEMBER
--						 AND vrxcvg.VERIF_STATUS_C IN ('1','12','13','23','26','6','8') --VERIFIED STATUS

--					)cvgvrx									ON ENC.COVERAGE_ID = cvgvrx.VERIF_RECORD_IDNT 
--																AND hsp.HOSP_ADMSN_TIME>=cvgvrx.LAST_STAT_CHNG_DTTM
--																AND hsp.HOSP_ADMSN_TIME<=CAST(cvgvrx.NEXT_REVIEW_DATE AS DATE)

--BENEFIT/COVERAGE VERIFICATION 
LEFT OUTER JOIN (
					SELECT  
						vrxcvg.VERIF_RECORD_IDNT
						,vrxcvg.LAST_STAT_CHNG_DTTM
						,vrxcvg.LAST_VERIF_USER_ID
						,vrxcvg.VERIF_STATUS_C
						,vrxcvg.NEXT_REVIEW_DATE
						,vrxcvg.VERIF_CONFRM_ID
						,vrxcvg.RECORD_CREATION_DT
						,vrxcvg.enc_CSN
						,emp.NAME
					 FROM  CLARITY.dbo.VERIFICATION vrxcvg
					 LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = vrxcvg.LAST_VERIF_USER_ID
					 WHERE 1=1
						 AND vrxcvg.VERIFICATION_TYPE_C ='8' --ENCOUNTER BENEFIT VERIFICATION
						 AND vrxcvg.VERIF_STATUS_C IN ('1','12','13','23','26','6','8') --VERIFIED STATUS

					)cvgvrx									ON hsp.PAT_ENC_CSN_ID = cvgvrx.ENC_CSN 

--BENEFIT/COVERAGE VERIFICATION VIA RTE	
--LEFT OUTER JOIN 		(SELECT 
--							 cvgrte.CVG_ID
--							 ,cvgrte.QUERY_DATE
--							 ,cvgrte.SENT_TRUE_INST_DTTM
--							 ,cvgrte.RCVD_TRUE_INST_DTTM
--							 ,hno.RTE_TRIGGER_USER_ID
--							 ,emp.NAME
--						 FROM CLARITY.dbo.CVG_RTE_QUERY cvgrte
--						 INNER JOIN CLARITY.dbo.HNO_INFO hno		ON 	CVGRTE.RESP_ID = hno.NOTE_ID
--						 LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = hno.RTE_TRIGGER_USER_ID
--						 ) cvgrte							ON enc.COVERAGE_ID = cvgrte.CVG_ID AND cvgrte.QUERY_DATE=CAST(hsp.HOSP_ADMSN_TIME AS DATE)


--HOSPITAL ACCOUNT VERIFICATION 
LEFT OUTER JOIN (
					SELECT  
						vrxhar.VERIF_RECORD_IDNT
						,vrxhar.LAST_STAT_CHNG_DTTM
						,vrxhar.LAST_VERIF_USER_ID
						,vrxhar.VERIF_STATUS_C
						,vrxhar.NEXT_REVIEW_DATE
						,vrxhar.VERIF_CONFRM_ID
						,vrxhar.RECORD_CREATION_DT
						,emp.NAME
					 FROM  CLARITY.dbo.VERIFICATION vrxhar
					 LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = vrxhar.LAST_VERIF_USER_ID
					 WHERE 1=1
						 AND vrxhar.VERIFICATION_TYPE_C ='4' --HOSPITAL ACCOUNT
						 AND vrxhar.VERIF_STATUS_C IN ('1','12','13','23','26','6','8') --VERIFIED STATUS

					)harvrx									ON hsp.HSP_ACCOUNT_ID = harvrx.VERIF_RECORD_IDNT 
																AND hsp.HOSP_ADMSN_TIME>=harvrx.LAST_STAT_CHNG_DTTM
																AND CAST(hsp.HOSP_ADMSN_TIME AS DATE)<=CAST(harvrx.NEXT_REVIEW_DATE AS DATE)



--ADMISSION 

LEFT OUTER JOIN (
				SELECT hx.*, emp.NAME, ROW_NUMBER() OVER (PARTITION BY hx.PAT_ENC_CSN_ID ORDER BY hx.UPDATE_TIME DESC) 'RNo' --LAST UPDATED RECORD	
				FROM CLARITY.dbo.PAT_ENC_STAT_HX hx	
				LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = hx.UPDATE_USER_ID			
				WHERE 1=1
				AND hx.UPDATED_CONF_STAT_C ='1' --CONFIRMED
				AND hx.UPDATED_ENC_STAT_C IN ('2','6') --ADMISSIONS /HOV
				)admhx											ON admhx.PAT_ENC_CSN_ID = hsp.PAT_ENC_CSN_ID AND admhx.RNo='1'




--PATIENT TYPE
LEFT OUTER JOIN CLARITY.dbo.PATIENT_TYPE pttyp				ON hsp.PAT_ID	=	pttyp.PAT_ID
LEFT OUTER JOIN CLARITY.dbo.ZC_PATIENT_TYPE zcpttyp			ON pttyp.PATIENT_TYPE_C = zcpttyp.PATIENT_TYPE_C


--AUTH/CERT

LEFT OUTER JOIN CLARITY.dbo.REFERRAL_CVG_AUTH rfl			ON ENC.COVERAGE_ID = rfl.AUTH_CERT_CVG_ID
																and ENC.REFERRAL_ID = RFL.REFERRAL_ID

--MSPQ
LEFT OUTER JOIN CLARITY.dbo.PAT_ENC_MSP mspq				ON mspq.PAT_ENC_CSN_ID = hsp.PAT_ENC_CSN_ID


--DOCUMENTS 
--Insurance Waiver Form
LEFT OUTER JOIN (
				SELECT  doc.*, emp.NAME
					FROM CLARITY.dbo.DOC_INFORMATION doc
					LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = doc.RECV_BY_USER_ID
					WHERE doc.DOC_INFO_TYPE_C IN ('204100014') --Insurance Waiver Form
					)dcswv									ON hsp.PAT_ENC_CSN_ID = dcswv.DOC_CSN

--Important Message from Medicare
LEFT OUTER JOIN (
				SELECT  doc.*, emp.NAME
					FROM CLARITY.dbo.DOC_INFORMATION doc
					LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = doc.RECV_BY_USER_ID
					WHERE doc.DOC_INFO_TYPE_C IN ('204100012') -- Important Message from Medicare
					)dcsmc									ON hsp.PAT_ENC_CSN_ID = dcsmc.DOC_CSN

--Notice of Admission
LEFT OUTER JOIN (
				SELECT  doc.*, emp.NAME
					FROM CLARITY.dbo.DOC_INFORMATION doc
					LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = doc.RECV_BY_USER_ID
					WHERE doc.DOC_INFO_TYPE_C IN ('310100001')--Notice of Admission
					)dcsadm									ON hsp.PAT_ENC_CSN_ID = dcsadm.DOC_CSN


--RTE
LEFT OUTER JOIN (
					SELECT 
					rte1.PAT_ID
					,rte1.RTE_PAYOR_ID
					,rte1.RTE_PLAN_ID
					,rte1.RTE_RESP_STATUS_C
					,rte1.RTE_ACTION_C
					,rte1.RTE_SENT_TRUE_DTTM
					,rte1.RTE_RCVD_TRUE_DTTM
					,hno.RTE_TRIGGER_USER_ID
					,emp.NAME

					FROM CLARITY.dbo.RTE_PATIENT_QUERY rte1
					INNER JOIN CLARITY.dbo.HNO_INFO hno		ON 	rte1.RTE_HNO_ID = hno.NOTE_ID
					LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP emp ON emp.USER_ID = hno.RTE_TRIGGER_USER_ID
					WHERE 1=1
					AND rte1.RTE_PAYOR_ID IS NOT NULL
				)rte										ON rte.PAT_ID = hsp.PAT_ID AND CAST(hsp.HOSP_ADMSN_TIME AS DATE) =CAST(rte.RTE_SENT_TRUE_DTTM AS DATE)

																

--MYCHART STATUS
LEFT OUTER JOIN CLARITY.dbo.PATIENT_MYC myc					ON hsp.PAT_ID = myc.PAT_ID


--SELF PAYMENT 
LEFT OUTER JOIN CLARITY.dbo.PAT_ENC_SELF_PMT slfpmt			ON enc.PAT_ENC_CSN_ID = slfpmt.PAT_ENC_CSN_ID


--USER INFO

--SCHEDULING USER
LEFT OUTER JOIN (
					SELECT 
						 emp.USER_ID
						 ,emp.SYSTEM_LOGIN
						 ,EMP.NAME		'USER_NAME'
						 ,emp.LNK_SEC_TEMPLT_ID
						 ,tmp.NAME		'TEMPLATE_NAME'
						 ,emprl.DEFAULT_USER_ROLE
						 FROM CLARITY.dbo.CLARITY_EMP emp
						 INNER JOIN CLARITY.dbo.CLARITY_EMP_ROLE emprl			ON emp.USER_ID = emprl.USER_ID AND LINE ='1'  --ONLY PRIMARY USER ROLE 
						 INNER JOIN CLARITY.dbo.CLARITY_EMP tmp					ON emp.LNK_SEC_TEMPLT_ID = tmp.USER_ID
			    --)scdemp														ON pndcrtd.UPDATE_USER_ID = scdemp.USER_ID
			    )scdemp														ON hx.UPDATE_USER_ID = scdemp.USER_ID


--REGISTRATION USER
LEFT OUTER JOIN (
					SELECT 
						 emp.USER_ID
						 ,emp.SYSTEM_LOGIN
						 ,EMP.NAME		'USER_NAME'
						 ,emp.LNK_SEC_TEMPLT_ID
						 ,tmp.NAME		'TEMPLATE_NAME'
						 ,emprl.DEFAULT_USER_ROLE
						 FROM CLARITY.dbo.CLARITY_EMP emp
						 INNER JOIN CLARITY.dbo.CLARITY_EMP_ROLE emprl			ON emp.USER_ID = emprl.USER_ID AND LINE ='1'  --ONLY PRIMARY USER ROLE 
						 INNER JOIN CLARITY.dbo.CLARITY_EMP tmp					ON emp.LNK_SEC_TEMPLT_ID = tmp.USER_ID
			    )regemp														ON REG.USER_ID = regemp.USER_ID

--PATIENT VERIFICATION
/*LEFT OUTER JOIN (
					SELECT 
						 emp.USER_ID
						 ,emp.SYSTEM_LOGIN
						 ,EMP.NAME		'USER_NAME'
						 ,emp.LNK_SEC_TEMPLT_ID
						 ,tmp.NAME		'TEMPLATE_NAME'
						 ,emprl.DEFAULT_USER_ROLE
						 FROM CLARITY.dbo.CLARITY_EMP emp
						 INNER JOIN CLARITY.dbo.CLARITY_EMP_ROLE emprl			ON emp.USER_ID = emprl.USER_ID AND LINE ='1'  --ONLY PRIMARY USER ROLE 
						 INNER JOIN CLARITY.dbo.CLARITY_EMP tmp					ON emp.LNK_SEC_TEMPLT_ID = tmp.USER_ID
			    )ptvrxemp														ON ptvrx.LAST_VERIF_USER_ID = ptvrxemp.USER_ID
*/
--COVERAGE VERIFICATION
LEFT OUTER JOIN (
					SELECT 
						 emp.USER_ID
						 ,emp.SYSTEM_LOGIN
						 ,EMP.NAME		'USER_NAME'
						 ,emp.LNK_SEC_TEMPLT_ID
						 ,tmp.NAME		'TEMPLATE_NAME'
						 ,emprl.DEFAULT_USER_ROLE
						 FROM CLARITY.dbo.CLARITY_EMP emp
						 INNER JOIN CLARITY.dbo.CLARITY_EMP_ROLE emprl			ON emp.USER_ID = emprl.USER_ID AND LINE ='1'  --ONLY PRIMARY USER ROLE 
						 INNER JOIN CLARITY.dbo.CLARITY_EMP tmp					ON emp.LNK_SEC_TEMPLT_ID = tmp.USER_ID
			    --)cvgvrxemp														ON cvgrte.RTE_TRIGGER_USER_ID = cvgvrxemp.USER_ID
			    )cvgvrxemp														ON cvgvrx.LAST_VERIF_USER_ID = cvgvrxemp.USER_ID

--HAR VERIFICATION
LEFT OUTER JOIN (
					SELECT 
						 emp.USER_ID
						 ,emp.SYSTEM_LOGIN
						 ,EMP.NAME		'USER_NAME'
						 ,emp.LNK_SEC_TEMPLT_ID
						 ,tmp.NAME		'TEMPLATE_NAME'
						 ,emprl.DEFAULT_USER_ROLE
						 FROM CLARITY.dbo.CLARITY_EMP emp
						 INNER JOIN CLARITY.dbo.CLARITY_EMP_ROLE emprl			ON emp.USER_ID = emprl.USER_ID AND LINE ='1'  --ONLY PRIMARY USER ROLE 
						 INNER JOIN CLARITY.dbo.CLARITY_EMP tmp					ON emp.LNK_SEC_TEMPLT_ID = tmp.USER_ID
			    )harvrxemp														ON harvrx.LAST_VERIF_USER_ID = harvrxemp.USER_ID


--ADMISSION CONFIRMATION
LEFT OUTER JOIN (
					SELECT 
						 emp.USER_ID
						 ,emp.SYSTEM_LOGIN
						 ,EMP.NAME		'USER_NAME'
						 ,emp.LNK_SEC_TEMPLT_ID
						 ,tmp.NAME		'TEMPLATE_NAME'
						 ,emprl.DEFAULT_USER_ROLE
						 FROM CLARITY.dbo.CLARITY_EMP emp
						 INNER JOIN CLARITY.dbo.CLARITY_EMP_ROLE emprl			ON emp.USER_ID = emprl.USER_ID AND LINE ='1'  --ONLY PRIMARY USER ROLE 
						 INNER JOIN CLARITY.dbo.CLARITY_EMP tmp					ON emp.LNK_SEC_TEMPLT_ID = tmp.USER_ID
			    )admemp														ON admhx.UPDATE_USER_ID = admemp.USER_ID


--CANCELLATION OF PRE-ADMISSION
LEFT OUTER JOIN (
					SELECT *-- top 10 *
					FROM  PAT_ENC_STAT_HX hx
					WHERE  1=1
					AND  hx.UPDATED_ENC_STAT_C ='3' --cancelled
					) cncl															ON hsp.PAT_ENC_CSN_ID = cncl.PAT_ENC_CSN_ID


--WQ
--LEFT OUTER JOIN    CLARITY.dbo.REG_HX_AFF_RULE_RECS  CER			ON reg.REG_HX_EVENT_ID = CER.REG_HX_EVENT_ID
--LEFT OUTER JOIN		CLARITY.dbo.CL_CHRG_EDIT_RULE RL					ON CER.REG_HX_AFF_RULE_ID = RL.RULE_ID


--HB
--INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS AS TX 
--ON hsp.HSP_ACCOUNT_ID = TX.HSP_ACCOUNT_ID 
--AND tx.TX_TYPE_HA_C <> 1


--LEFT OUTER JOIN CLARITY.dbo.ZC_PEND_RECRD_TYPE zcrdc		ON pnd.PEND_RECRD_TYPE_C = zcrdc.PEND_RECRD_TYPE_C	
LEFT OUTER JOIN CLARITY.dbo.ZC_PAT_SERVICE svc				ON hsp.HOSP_SERV_C = svc.HOSP_SERV_C
LEFT OUTER JOIN CLARITY.dbo.ZC_ADM_SOURCE admsrc			ON hsp.ADMIT_SOURCE_C = admsrc.ADMIT_SOURCE_C 
LEFT OUTER JOIN CLARITY.dbo.ZC_HOSP_ADMSN_TYPE admtyp		ON hsp.HOSP_ADMSN_TYPE_C = admtyp.HOSP_ADMSN_TYPE_C
LEFT OUTER JOIN CLARITY.dbo.CLARITY_DEP dep					ON hsp.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN CLARITY.dbo.ZC_ACCOMMODATION acm			ON hsp.ACCOMMODATION_C = acm.ACCOMMODATION_C
LEFT OUTER JOIN CLARITY.dbo.ZC_PRE_CERT_STATUS certsts		ON rfl.PRE_CERT_STATUS_C = certsts.PRE_CERT_STATUS_C
LEFT OUTER JOIN CLARITY.dbo.ZC_MSP_COMPLETION zcmsp			ON mspq.MSP_STATUS_C = zcmsp.MSP_COMPLETION_C
LEFT OUTER JOIN CLARITY.dbo.ZC_DOC_STAT zcwvst				ON dcswv.DOC_STAT_C = zcwvst.DOC_STAT_C
LEFT OUTER JOIN CLARITY.dbo.ZC_DOC_STAT zcmcst				ON dcsmc.DOC_STAT_C = zcmcst.DOC_STAT_C
LEFT OUTER JOIN CLARITY.dbo.ZC_DOC_STAT zcadmst				ON dcsadm.DOC_STAT_C = zcadmst.DOC_STAT_C
LEFT OUTER JOIN CLARITY.dbo.ZC_RTE_RESP_STATUS zcrtest		ON rte.RTE_RESP_STATUS_C = zcrtest.RTE_RESP_STATUS_C
LEFT OUTER JOIN CLARITY.dbo.ZC_MYCHART_STATUS zcmyc			ON myc.MYCHART_STATUS_C = zcmyc.MYCHART_STATUS_C
LEFT OUTER JOIN CLARITY.dbo.ZC_CANCEL_REASON cnlrsn			ON enc.CANCEL_REASON_C = cnlrsn.CANCEL_REASON_C
LEFT OUTER JOIN CLARITY.dbo.CLARITY_EPM epm					ON cvg.PAYOR_ID = epm.PAYOR_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_EPP epp					ON cvg.PLAN_ID = epp.BENEFIT_PLAN_ID
LEFT OUTER JOIN CLARITY.dbo.ZC_PA_UNDO_RSN undorsn			ON cncl.UPDATE_REASON_EPT_C = undorsn.PREADM_UNDO_RSN_C

 
 WHERE 1=1

 AND idx.IDENTITY_TYPE_ID = '14' -- MRN
 --AND hsp.CONTACT_DATE>='1/1/2021'
 AND hsp.CONTACT_DATE>='7/1/2020'
 AND hsp.CONTACT_DATE<'3/1/2021'
 --AND pnd.PEND_EVENT_TYPE_C='1'		--admissions
 --AND ISNULL(pnd.PEND_RECRD_TYPE_C,'0')<>'2'  --hov??
 --AND hsp.PAT_ENC_CSN_ID ='200036394741'
 -- AND HSP.PAT_ID = 'Z1548267'
 --and pnd.PEND_ID='6150896'
 --and idx.identity_id='3114436'
 AND hx.UPDATED_ENC_STAT_C ='1' --PREADMISSION
 --AND hx.UPDATED_CONF_STAT_C <>'3' -- NOT CANCELLED
AND  hx.UPDATED_CONF_STAT_C in ('1') --CONFIRMED PREADMISSION

ORDER BY hsp.CONTACT_DATE
                   ,hsp.PAT_ENC_CSN_ID

 




