USE CLARITY

-----  "REFERRALS BY" Report  "REFERRAL_SOURCE  --> PROV_TYPE" CHANGED TO ZC_REF_PROV_TYPE --> NAME"
-----  DEPRECEATED COLUMN "REFERRAL_SOURCE  --> PROV_TYPE"; USE "REFERRAL_SOURCE  --> REF_PROV_TYPE_C INSTEAD"
-----  Updated on 5/21/2018 by  "Lakshmi Alla"

DECLARE	@startdate	SMALLDATETIME
DECLARE	@enddate	SMALLDATETIME
DECLARE	@dept		VARCHAR(8000)
DECLARE	@rflc		VARCHAR(8000)

--SET @startdate = '1/1/2020'
SET @startdate = '7/1/2019 00:00 AM'
SET @enddate = '2/9/2020 11:59 PM'
SET @dept	= '10228012' -- NRDG COMMUNITY MED
SET @rflc	= '3' -- Outgoing
  
 /*******************************************************************************************
WHAT:	Referred By
WHO :	Dayna Monaghan/Christine Kelly	
WHEN:	04/11/2017
WHY :	Reporting on referrals by a department

-------------------------------------------------------------------------------------------------------------------------
--INFO: 
--      INPUTS: REFERRAL
				REFERRAL_ORDER_ID
				ORDER_PROC
				ZC_RFL_CLASS
				ZC_RFL_STATUS
				ZC_REFD_TO_SPEC
				CLARITY_DEP
				CLARITY_POS
				REFERRAL_SOURCE
				CLARITY_SER
				ZC_NOTE_SER
                  
--      OUTPUTS: 
   
   	
--------------------------------------------------------------------------------------------
MODS:  

*******************************************************************************************/
  SELECT
      r.REFD_BY_DEPT_ID          AS RFRL_BY_DEPT_ID
    , d1.EXTERNAL_NAME           AS RFRL_BY_DEPT_NME
	, r.REFD_TO_DEPT_ID          AS RFRL_TO_DEPT_ID
    , d2.EXTERNAL_NAME           AS RFRL_TO_DEPT_NME
    , CAST(r.ENTRY_DATE AS DATE) AS RFRL_DATE
	, r.EXP_DATE                 AS RFRL_EXP_DATE
	, r.REFERRAL_ID,
     rh.LINE,
     rh.CHANGE_DATE,
     rh.CHANGE_TYPE_C,
	 rhct.NAME					AS CHANGE_TYPE_NAME,
     rh.CHANGE_USER_ID,
	 emp.NAME                   AS CHANGE_USER_NAME,
     rh.PREVIOUS_VALUE,
     rh.CHANGE_DATETIME
    , r.ACTUAL_NUM_VISITS
    , r2.AP_CLAIM_COUNT
	, r.RFL_CLASS_C
    , rc.NAME                    AS RFRL_CLASS_NME
	, r3.AUTH_CERT_YN
	, r.RFL_TYPE_C
	, rt.NAME					AS RFL_TYPE_NAME
	, r.PRIORITY_C
	, rp.NAME					AS PRIORITY_NAME
	, r.RFL_SENS_C
	, rse.NAME					AS RFL_SENS_NAME
	, r.SCHED_STATUS_C
	, rst.NAME					AS SCHED_STATUS_NAME
	, rf.LINE					AS REFERRAL_FLAGS_LINE
	, rf.FLAG_C
	, rfc.NAME			AS FLAG_NAME,
	--, rh.REFERRAL_ID,
	 --RFL_APPTS.PAT_ENC_CSN_ID,
	 RFL_APPTS.APPT_MADE_DATE,
	 RFL_APPTS.APPT_MADE_DTTM,
	 --RFL_APPTS.CONTACT_DATE,
	 --RFL_APPTS.APPT_STATUS_C,
	 --RFL_APPTS.APPT_STATUS_NAME,
	 RFL_APPTS.ACTUAL_CNT AS SCHEDULED_VISITS,
	 RFL_APPTS.APPT_MADE_DTTM AS FIRST_APPT_MADE, -- First scheduled appointment datetime
	 RFL_APPTS.APPT_DATE AS FIRST_APPT,  -- First scheduled appointment
	 RFL_APPTS.SCHEDULED_CNT,
	 RFL_APPTS.COMPLETED_CNT,
	 RFL_APPTS.CANCELED_CNT,
	 RFL_APPTS.NO_SHOW_CNT,
	 RFL_APPTS.ARRIVED_CNT,
     rh.AUTH_HX_ITEM_NUMBER,
     rh.AUTH_HX_ITEM_VALUE,
     rh.AUTH_HX_EVENT_NO,
     rh.AUTH_HX_NOTE_ID,
     rh.CHANGE_LOCAL_DTTM,
     rs.NAME                    AS RFRL_STATUS_NME
    ,prvtyp.NAME                AS RFRL_BY_PRVDR_TYPE_NME
    ,prvdr1.REFERRING_PROV_NAM  AS RFRL_BY_PRVDR_NME
    ,pt2.NAME                   AS RFRL_TO_PRVDR_TYPE_NME
    ,prvdr2.PROV_NAME           AS RFRL_TO_PRVDR_NME
    ,rts.NAME                   AS RFRL_TO_SPCLTY_NME
    ,prc.DISPLAY_NAME           AS RFRL_ORDER_DSCR
  FROM REFERRAL AS r WITH (NOLOCK)
  INNER JOIN REFERRAL_ORDER_ID    AS roi    WITH (NOLOCK) ON r.REFERRAL_ID          = roi.REFERRAL_ID
  LEFT OUTER JOIN ORDER_PROC      AS prc    WITH (NOLOCK) ON roi.ORDER_ID           = prc.ORDER_PROC_ID
  LEFT OUTER JOIN ZC_RFL_CLASS    AS rc     WITH (NOLOCK) ON r.RFL_CLASS_C          = rc.RFL_CLASS_C
  LEFT OUTER JOIN ZC_RFL_STATUS   AS rs     WITH (NOLOCK) ON r.RFL_STATUS_C         = rs.RFL_STATUS_C
  LEFT OUTER JOIN ZC_REFD_TO_SPEC AS rts    WITH (NOLOCK) ON r.REFD_TO_SPEC_C       = rts.REFD_TO_SPEC_C
  LEFT OUTER JOIN CLARITY_DEP     AS d1     WITH (NOLOCK) ON r.REFD_BY_DEPT_ID      = d1.DEPARTMENT_ID
  LEFT OUTER JOIN CLARITY_DEP     AS d2     WITH (NOLOCK) ON r.REFD_TO_DEPT_ID      = d2.DEPARTMENT_ID
  LEFT OUTER JOIN CLARITY_POS     AS pos1   WITH (NOLOCK) ON r.REFD_BY_LOC_POS_ID   = pos1.POS_ID
  LEFT OUTER JOIN REFERRAL_SOURCE AS prvdr1 WITH (NOLOCK) ON r.REFERRING_PROV_ID    = prvdr1.REFERRING_PROV_ID
  LEFT OUTER JOIN CLARITY_SER     AS prvdr2 WITH (NOLOCK) ON r.REFERRAL_PROV_ID     = prvdr2.PROV_ID
  LEFT OUTER JOIN ZC_NOTE_SER     AS pt2    WITH (NOLOCK) ON prvdr2.PROVIDER_TYPE_C = pt2.SERVICE_TYPE_C
  LEFT OUTER JOIN ZC_REF_PROV_TYPE AS prvtyp WITH (NOLOCK) ON prvdr1.REF_PROV_TYPE_C = prvtyp.REF_PROV_TYPE_C
  LEFT OUTER JOIN dbo.REFERRAL_HIST AS rh   WITH (NOLOCK) ON rh.REFERRAL_ID          = r.REFERRAL_ID
  LEFT OUTER JOIN dbo.CLARITY_EMP AS emp    WITH (NOLOCK) ON emp.USER_ID             = rh.CHANGE_USER_ID
  LEFT OUTER JOIN dbo.REFERRAL_2  AS r2     WITH (NOLOCK) ON r2.REFERRAL_ID          = r.REFERRAL_ID
  LEFT OUTER JOIN dbo.REFERRAL_3  AS r3		WITH (NOLOCK) ON r3.REFERRAL_ID			 = r.REFERRAL_ID
  LEFT OUTER JOIN dbo.ZC_RFL_TYPE AS rt     WITH (NOLOCK) ON rt.RFL_TYPE_C			 = r.RFL_TYPE_C
  LEFT OUTER JOIN dbo.ZC_RFL_PRIORITY AS rp WITH (NOLOCK) ON rp.PRIORITY_C           = r.PRIORITY_C
  LEFT OUTER JOIN dbo.ZC_RFL_SENS AS rse	WITH (NOLOCK) ON rse.RFL_SENS_C			 = r.RFL_SENS_C
  LEFT OUTER JOIN dbo.ZC_SCHED_STATUS AS rst WITH (NOLOCK) ON rst.SCHED_STATUS_C	 = r.SCHED_STATUS_C
  LEFT OUTER JOIN dbo.REFERRAL_FLAGS AS rf   WITH (NOLOCK) ON rf.REFERRAL_ID		 = r.REFERRAL_ID
  LEFT OUTER JOIN dbo.ZC_RFL_FLAG AS rfc    WITH (NOLOCK) ON rfc.RFL_FLAG_C          = rf.FLAG_C
  LEFT OUTER JOIN dbo.ZC_RFL_HST_CHG_TYP rhct WITH (NOLOCK) ON rhct.CHANGE_TYPE_C    = rh.CHANGE_TYPE_C
  --LEFT OUTER JOIN 
	 -- ( SELECT RFL.REFERRAL_ID RFL_ID, RFL_ENC.PAT_ENC_CSN_ID, RFL_ENC.APPT_MADE_DATE, RFL_ENC.APPT_MADE_DTTM, RFL_ENC.CONTACT_DATE, RFL_ENC.APPT_STATUS_C, RFL_ENC.APPT_STATUS_NAME
		--  FROM REFERRAL RFL
		--  INNER JOIN V_SCHED_APPT RFL_ENC ON RFL_ENC.REFERRAL_ID = RFL.REFERRAL_ID) RFL_APPTS ON RFL_APPTS.RFL_ID = r.REFERRAL_ID
		--  --WHERE RFL_ENC.APPT_STATUS_C IN (1,2,6) OR RFL_ENC.COMPLETED_STATUS_YN='Y' -- Scheduled, Completed, Arrived
		--  --GROUP BY RFL.REFERRAL_ID) RFL_APPTS ON RFL_APPTS.RFL_ID = r.REFERRAL_ID
   LEFT OUTER JOIN 
      ( SELECT RFL.REFERRAL_ID RFL_ID,
         COUNT(DISTINCT RFL_ENC.PAT_ENC_CSN_ID) ACTUAL_CNT,
         MIN(RFL_ENC.APPT_MADE_DATE) APPT_MADE_DATE, -- First scheduled appointment date
         MIN(RFL_ENC.APPT_MADE_DTTM) APPT_MADE_DTTM, -- First scheduled appointment datetime
         MIN(RFL_ENC.CONTACT_DATE) APPT_DATE,  -- First scheduled appointment
		 SUM(CASE WHEN RFL_ENC.APPT_STATUS_C = 1 THEN 1 ELSE 0 END) SCHEDULED_CNT,
		 SUM(CASE WHEN RFL_ENC.APPT_STATUS_C = 2 THEN 1 ELSE 0 END) COMPLETED_CNT,
		 SUM(CASE WHEN RFL_ENC.APPT_STATUS_C = 3 THEN 1 ELSE 0 END) CANCELED_CNT,
		 SUM(CASE WHEN RFL_ENC.APPT_STATUS_C = 4 THEN 1 ELSE 0 END) NO_SHOW_CNT,
		 SUM(CASE WHEN RFL_ENC.APPT_STATUS_C = 6 THEN 1 ELSE 0 END) ARRIVED_CNT
         FROM REFERRAL RFL
         INNER JOIN V_SCHED_APPT RFL_ENC ON RFL_ENC.REFERRAL_ID = RFL.REFERRAL_ID
         --WHERE RFL_ENC.APPT_STATUS_C IN (1,2,6) OR RFL_ENC.COMPLETED_STATUS_YN='Y' -- Scheduled, Completed, Arrived
         GROUP BY RFL.REFERRAL_ID) RFL_APPTS ON RFL_APPTS.RFL_ID = r.REFERRAL_ID
  --WHERE (r.ENTRY_DATE BETWEEN @startdate AND @enddate)
  WHERE (r.EXP_DATE BETWEEN @startdate AND @enddate)
    AND (r.REFD_BY_DEPT_ID IN (@dept))
    --AND (r.REFD_TO_DEPT_ID = 10211008)
	--AND r.RFL_CLASS_C = 3
	--AND (r.RFL_CLASS_C IN (@rflc))
	--AND (r.RFL_CLASS_C IS NOT NULL AND r.RFL_CLASS_C <> 2)
	AND (rhct.NAME LIKE '%Schedul%' AND rhct.NAME NOT IN ('RFLEOD','CADENCEEOD'))
	AND (rh.CHANGE_USER_ID NOT IN ('RFLEOD'))
	--AND RFL_APPTS.ACTUAL_CNT IS NOT NULL
	AND r.ACTUAL_NUM_VISITS IS NOT NULL
  --ORDER BY RFRL_CLASS_NME, r.ENTRY_DATE, r.REFERRAL_ID, rh.LINE
  --ORDER BY r.REFD_BY_DEPT_ID, RFRL_CLASS_NME, r.REFERRAL_ID, r.ENTRY_DATE, rh.LINE, RFL_APPTS.APPT_MADE_DTTM
  ORDER BY r.REFD_BY_DEPT_ID, r.REFD_TO_DEPT_ID, RFRL_CLASS_NME, r.REFERRAL_ID, r.ENTRY_DATE--, rh.LINE--, RFL_APPTS.APPT_MADE_DTTM