USE CLARITY
GO

DECLARE @EVENT_START_UTC_DTTM DATETIME
                , @EVENT_END_UTC_DTTM DATETIME

SET @EVENT_START_UTC_DTTM = CLARITY.EPIC_UTIL.EFN_LOCAL_TO_UTC('7/1/2020 00:00')
SET @EVENT_END_UTC_DTTM = CLARITY.EPIC_UTIL.EFN_LOCAL_TO_UTC('3/1/2021 00:00')

SELECT  @EVENT_START_UTC_DTTM, @EVENT_END_UTC_DTTM

SELECT DISTINCT
IDX.IDENTITY_ID
,pt.REG_HX_AFF_PAT_CSN
,enc.HSP_ACCOUNT_ID
,hx.REG_HX_INST_UTC_DTTM
--,CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(hx.REG_HX_INST_UTC_DTTM) AS REG_HX_INST_LOCAL_DTTM
,enc.CONTACT_DATE
--,pt.REG_HX_AFF_PAT_ID
,hx.REG_HX_AFF_WQ_ID
,wq.WORKQUEUE_NAME
--,hx.REG_HX_AFF_WQ_ITEM_ID
,rl.REG_HX_AFF_RULE_ID
,clrl.RULE_NAME


FROM CLARITY.dbo.REG_HX hx
INNER JOIN CLARITY.dbo.REG_HX_AFF_PAT_RECS pt			ON hx.REG_HX_EVENT_ID = pt.REG_HX_EVENT_ID
INNER JOIN CLARITY.dbo.IDENTITY_ID idx					ON pt.REG_HX_AFF_PAT_ID = idx.PAT_ID
INNER JOIN CLARITY.dbo.PAT_ENC enc						ON pt.REG_HX_AFF_PAT_CSN = enc.PAT_ENC_CSN_ID
LEFT OUTER JOIN CLARITY.dbo.REG_HX_AFF_RULE_RECS rl		ON hx.REG_HX_EVENT_ID = rl.REG_HX_EVENT_ID	
LEFT OUTER JOIN CLARITY.dbo.CL_CHRG_EDIT_RULE clrl		ON rl.REG_HX_AFF_RULE_ID = clrl.RULE_ID
LEFT OUTER JOIN CLARITY.dbo.PAT_WQ wq					ON hx.REG_HX_AFF_WQ_ID = wq.WORKQUEUE_ID
LEFT OUTER JOIN CLARITY.dbo.PAT_WQ_ITEMS itm			ON hx.REG_HX_AFF_WQ_ITEM_ID = itm.ITEM_ID


WHERE 1=1
AND hx.REG_HX_EVENT_C IN ('71','73')--workqueue contact created/ rule added
AND idx.IDENTITY_TYPE_ID ='14'
--AND REG_HX_AFF_WQ_ID IS NOT NULL
--AND EPIC_UTIL.EFN_UTC_TO_LOCAL(REG_HX_INST_UTC_DTTM) >='7/1/2020'
--AND EPIC_UTIL.EFN_UTC_TO_LOCAL(REG_HX_INST_UTC_DTTM) <'3/01/2021'
--AND REG_HX_INST_UTC_DTTM >='7/1/2020'
--AND REG_HX_INST_UTC_DTTM <'1/01/2021'
--AND enc.CONTACT_DATE>='7/1/2020'
--AND enc.CONTACT_DATE<'3/1/2021'
--AND enc.CONTACT_DATE='7/1/2020'
--AND CLARITY.EPIC_UTIL.EFN_UTC_TO_LOCAL(hx.REG_HX_INST_UTC_DTTM) BETWEEN '7/1/2020 00:00' AND '7/1/2020 23:59'
AND hx.REG_HX_INST_UTC_DTTM BETWEEN @EVENT_START_UTC_DTTM AND @EVENT_END_UTC_DTTM

ORDER BY idx.IDENTITY_ID
                   ,pt.REG_HX_AFF_PAT_CSN
				   ,enc.HSP_ACCOUNT_ID
