USE CLARITY

SET NOCOUNT ON;

IF OBJECT_ID('tempdb..#CL_SSA ') IS NOT NULL
DROP TABLE #CL_SSA

IF OBJECT_ID('tempdb..#CL_SSA_RECALL_HX ') IS NOT NULL
DROP TABLE #CL_SSA_RECALL_HX

IF OBJECT_ID('tempdb..#CL_SSA_PROV_DEPT ') IS NOT NULL
DROP TABLE #CL_SSA_PROV_DEPT

IF OBJECT_ID('tempdb..#RptgTemp ') IS NOT NULL
DROP TABLE #RptgTemp

SELECT [ACTION_ID]
      --,[CM_PHY_OWNER_ID]
      --,[CM_LOG_OWNER_ID]
      ,[REC_STATE_C] -- Hidden, Soft-Deleted, Active (Normal)
	  ,zcrs2.NAME AS REC_STATE_NAME
      ,ssa.[PAT_ID]
	  ,pat.PAT_NAME
      ,[RECORD_TYPE_C]
	  ,zcrt5.NAME AS RECORD_TYPE_NAME
      ,[TEMPLATE_ID]
      ,ssa.[RECALL_STATUS_C]
	  ,zcrs.NAME AS RECALL_STATUS_NAME
      ,[RECALL_EXPIRE_DT]
      ,ssa.[PRE_REQ_STATUS_C]
	  ,zcprs.NAME AS PRE_REQ_STATUS_NAME
      ,[RECALL_NOTIF_DATE]
      ,[RECALL_DT]
      ,ssa.[HOW_NOTIFIED_C]
	  ,zchn.NAME AS HOW_NOTIFIED_NAME
      ,ssa.[PRC_ID]
	  ,prc.PRC_NAME
      ,[SPEC_PRV_TYPE_BM]
      ,[LETTER_ID]
      ,[MIN_TIME_UNIT_C]
      ,[MIN_TIME_AMOUNT]
      ,[MAX_TIME_UNIT_C]
      ,[MAX_TIME_AMOUNT]
      ,[OVERRULE_C]
      ,[PRE_REQ_LINK_TYPE_C]
      ,[BEST_PRACTICE_ID]
      ,[PRNTG_DEPT_ID]
      ,ssa.[DEPT_PROV_TYPE_C]
	  ,zcdpt.NAME AS DEPT_PROV_TYPE_NAME
      ,[RECALL_PHONE_NUM]
      ,[BLOCK_AUTO_CALL_YN]
      ,[RECALL_PHONE_TYPE_C]
      ,[INCL_PHONE_EXT_DT]
      ,[CREATE_METHOD_C]
	  ,zccm2.NAME AS CREATE_METHOD_NAME
      ,[RECALL_VALID_PHONE]
  INTO #CL_SSA
  FROM [dbo].[CL_SSA] ssa
  LEFT OUTER JOIN dbo.CLARITY_PRC prc
  ON prc.PRC_ID = ssa.PRC_ID
  LEFT OUTER JOIN dbo.PATIENT pat
  ON pat.PAT_ID = ssa.PAT_ID
  LEFT OUTER JOIN dbo.ZC_RECORD_STATUS_2 zcrs2
  ON zcrs2.RECORD_STATUS_2_C = ssa.REC_STATE_C
  LEFT OUTER JOIN dbo.ZC_RECORD_TYPE_5 zcrt5
  ON zcrt5.RECORD_TYPE_5_C = ssa.RECORD_TYPE_C
  LEFT OUTER JOIN dbo.ZC_PRE_REQ_STATUS zcprs
  ON zcprs.PRE_REQ_STATUS_C = ssa.PRE_REQ_STATUS_C
  LEFT OUTER JOIN dbo.ZC_RECALL_STATUS zcrs
  ON zcrs.RECALL_STATUS_C = ssa.RECALL_STATUS_C
  LEFT OUTER JOIN dbo.ZC_HOW_NOTIFIED zchn
  ON zchn.HOW_NOTIFIED_C = ssa.HOW_NOTIFIED_C
  LEFT OUTER JOIN dbo.ZC_DEPT_PROV_TYPE zcdpt
  ON zcdpt.DEPT_PROV_TYPE_C = ssa.DEPT_PROV_TYPE_C
  LEFT OUTER JOIN dbo.ZC_CREATE_METHOD_2 zccm2
  ON zccm2.CREATE_METHOD_2_C = ssa.CREATE_METHOD_C
  --WHERE ACTION_ID = 101
  ORDER BY ssa.ACTION_ID

  SELECT *
  FROM #CL_SSA
  WHERE ACTION_ID = 44173

SELECT [ACTION_ID]
      ,[LINE]
      ,ssahx.[CM_PHY_OWNER_ID]
      ,ssahx.[CM_LOG_OWNER_ID]
      ,[RECALL_STAT_HX_C]
	  ,zcrs.NAME AS [RECALL_STAT_HX_NAME]
      ,[REC_STAT_HX_INST]
      ,[REC_STAT_HX_EMP_ID]
	  ,emp.NAME AS [REC_STAT_HX_EMP_NAME]
	  ,emp.PROV_ID  AS [REC_STAT_HX_EMP_PROV_ID]
  INTO #CL_SSA_RECALL_HX
  FROM [dbo].[CL_SSA_RECALL_HX] ssahx
  LEFT OUTER JOIN dbo.ZC_RECALL_STATUS zcrs
  ON zcrs.RECALL_STATUS_C = ssahx.RECALL_STAT_HX_C
  LEFT OUTER JOIN dbo.CLARITY_EMP emp
  ON emp.USER_ID = ssahx.REC_STAT_HX_EMP_ID
  --WHERE ACTION_ID = 101
  ORDER BY ssahx.ACTION_ID
         , ssahx.REC_STAT_HX_INST

SELECT *
FROM #CL_SSA_RECALL_HX
WHERE ACTION_ID = 44173

SELECT [ACTION_ID]
      ,[LINE]
	  ,ssapd.PROV_ID
	  ,ser.PROV_NAME
	  ,ssapd.DEP_ID
	  ,dep.DEPARTMENT_NAME
	  ,ssapd.DEPT_PROV_TYPE_C
	  ,zcdpt.NAME AS DEPT_PROV_TYPE_NAME
  INTO #CL_SSA_PROV_DEPT
  FROM [dbo].[CL_SSA_PROV_DEPT] ssapd
  LEFT OUTER JOIN dbo.CLARITY_SER ser
  ON ser.PROV_ID = ssapd.PROV_ID
  LEFT OUTER JOIN dbo.CLARITY_DEP dep
  ON dep.DEPARTMENT_ID = ssapd.DEP_ID
  LEFT OUTER JOIN dbo.ZC_DEPT_PROV_TYPE zcdpt
  ON zcdpt.DEPT_PROV_TYPE_C = ssapd.DEPT_PROV_TYPE_C
  --WHERE ACTION_ID = 101
  WHERE ssapd.LINE = 1
  OR (ssapd.LINE > 1 AND ssapd.PROV_ID IS NOT NULL)
  ORDER BY ssapd.ACTION_ID
         , ssapd.LINE

SELECT *
FROM #CL_SSA_PROV_DEPT
WHERE ACTION_ID = 44173
--WHERE LINE > 1 AND PROV_ID IS NULL
ORDER BY ACTION_ID
       , LINE
--ORDER BY DEP_ID
--       , ACTION_ID
--       , LINE
/*
SELECT ssa.ACTION_ID
      ,ssahx.REC_STAT_HX_INST AS REC_STAT_HX_INST_NEW
      ,ssa.RECALL_NOTIF_DATE
	  ,ssa.RECALL_DT
	  ,ssapd.LINE
	  ,ssapd.PROV_NAME
	  ,ssapd.DEPARTMENT_NAME
INTO #RptgTemp
FROM #CL_SSA ssa
LEFT OUTER JOIN
(
	SELECT ACTION_ID
	      ,REC_STAT_HX_INST
	FROM #CL_SSA_RECALL_HX
	WHERE RECALL_STAT_HX_C = 10
) ssahx
ON ssahx.ACTION_ID = ssa.ACTION_ID
LEFT OUTER JOIN #CL_SSA_PROV_DEPT ssapd
ON ssapd.ACTION_ID = ssa.ACTION_ID

SELECT *
FROM #RptgTemp
ORDER BY ACTION_ID
        ,LINE
*/
GO