/****** Script for SelectTopNRows command from SSMS  ******/
SELECT enc.[PAT_ENC_CSN_ID]
      , enc.[EFFECTIVE_DATE_DT]
      , enc.[PAT_ID]
      , enc.[ENC_PROV_ID]
      , enc.[ENC_DEPARTMENT_ID]
      , enc.[ENC_REV_LOC_ID]
      , enc.[ENC_SERV_AREA_ID]
      ,[APPT_PRC_ID]
      ,[IS_ON_DEMAND_VV_YN]
      , enc.[SCHED_BY_PAT_ONLINE_YN]
      ,enc.[TELEHEALTH_MODE_C]
	  ,tm.NAME AS TELEHEALTH_MODE_NAME
      ,enc.[DISP_ENC_TYPE_C]
	  ,enct.NAME AS DISP_ENC_TYPE_NAME
      ,[VIDEO_VISIT_ID]
      ,enc.[APPT_STATUS_C]
	  ,zas.NAME AS APPT_STATUS_NAME
	  , vst.RECORD_ID,
       --vst.PAT_ENC_CSN_ID,
       --vst.EFFECTIVE_DATE_DT,
       --vst.PAT_ID,
       --vst.ENC_PROV_ID,
       --vst.ENC_DEPARTMENT_ID,
       --vst.ENC_REV_LOC_ID,
       --vst.ENC_SERV_AREA_ID,
       vst.ENC_PRC_VT_ID,
       vst.SUCCESSFUL_CONNECT_YN,
       vst.ATTEMPTED_CONNECT_CNT,
       vst.MYPT_CONNECT_CNT,
       vst.PAT_QUEUE_CNT,
       vst.PAT_HARDWARE_FAILURE_CNT,
       vst.DISP_ENC_TYPE_C,
       vst.PAT_QUEUE_JOIN_UTC_DTTM,
       vst.PROV_JOIN_UTC_DTTM,
       vst.DURATION_PAT_TO_PROV_JOIN,
       vst.LEN_IN_SECONDS,
       vst.ON_DEMAND_VIDEO_VISIT_C,
       vst.SCHED_BY_PAT_ONLINE_YN,
       vst.MYCH_WEB_CONNECT_CNT,
       vst.MYCH_MOBILE_CONNECT_CNT,
       vst.MYCH_BEDSIDE_CONNECT_CNT,
       vst.HYPERSPACE_CONNECT_CNT,
       vst.EC_LINK_CONNECT_CNT,
       vst.HAIKU_CONNECT_CNT,
       vst.ROVER_CONNECT_CNT,
       vst.CAMERA_FAILURES_CNT,
       vst.MICROPHONE_FAILURES_CNT,
       vst.SPEAKER_FAILURES_CNT,
       vst.NETWORK_FAILURE_CNT,
       vst.LATE_START_SECONDS,
       vst.IS_INPATIENT_YN,
       vst.CONNCTD_PARTIES_NUM,
       vst.CANTO_CONNECT_CNT,
       vst.DIRECT_LINK_CONNECT_CNT,
       vst.DI_PHYS_MOBILE_CONNECT_CNT,
       vst.PAT_CLIENT_APP_TARGET_C,
       vst.PROV_CLIENT_APP_TARGET_C,
       vst.GENERIC_FAILURE_COUNT,
       vst.PROV_HARDWARE_FAILURE_CNT,
       vst.SUCCESSFUL_VISIT_YN,
       vst.MYCH_OUTPATIENT_VISIT_YN,
       vst.MYCH_INPATIENT_VISIT_YN,
       vst.DIRECT_LINK_PROV_CONNECT_CNT,
       vst.GROUP_LINK
  FROM [CLARITY].[dbo].[V_VIDEO_VISIT_ENC_STATS] enc
  INNER JOIN [CLARITY].[dbo].[V_VIDEO_VISIT_STATS] vst
  ON enc.VIDEO_VISIT_ID = vst.RECORD_ID
  LEFT OUTER JOIN CLARITY.dbo.ZC_APPT_STATUS zas
  ON zas.APPT_STATUS_C = enc.APPT_STATUS_C
  LEFT OUTER JOIN CLARITY.dbo.ZC_DISP_ENC_TYPE enct
  ON enct.DISP_ENC_TYPE_C = enc.DISP_ENC_TYPE_C
  LEFT OUTER JOIN CLARITY.dbo.ZC_TELEHEALTH_MODE tm
  ON tm.TELEHEALTH_MODE_C = enc.TELEHEALTH_MODE_C
  ----WHERE enc.PAT_ENC_CSN_ID = 200046867929
  ----WHERE enc.PAT_ENC_CSN_ID = 200049469596
  ----WHERE enc.PAT_ENC_CSN_ID = 200038000187
  ----WHERE enc.PAT_ENC_CSN_ID = 200044874088
  --WHERE enc.PAT_ENC_CSN_ID = 200050737712
  --WHERE enc.PAT_ENC_CSN_ID = 200050666630
  WHERE enc.PAT_ENC_CSN_ID = 200055535542
  --WHERE enc.PAT_ENC_CSN_ID IN (200046867929,200049469596)
