IF OBJECT_ID('tempdb..#ptnos ') IS NOT NULL
DROP TABLE #ptnos

SELECT [MED_REC_NO]
      ,[PT_NO]
	  ,COUNT(*) AS PT_NO_COUNT
	  ,SUM(CASE WHEN REL_ADDR_LINE1 IS NOT NULL THEN 1 ELSE 0 END) AS [NON_NULL_ADDR]
	  ,SUM(CASE WHEN REL_ADDR_LINE1 IS NULL THEN 1 ELSE 0 END) AS [NULL_ADDR]
  INTO #ptnos
  FROM [DS_HSDM_Prod].[HSDO].[vwCensus_Special_Guest_Program]
  GROUP BY MED_REC_NO, PT_NO

  SELECT *
  FROM #ptnos
  ORDER BY NON_NULL_ADDR