/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
       --[sk_Stage_Scheduled_Appointment]
       [APPT_DT]
      ,appt.[PAT_ENC_CSN_ID]
      ,[PAT_ID]
      ,[PAT_NAME]
      --,appt.[IDENTITY_ID]
      --,[MYCHART_STATUS_C]
      --,[MYCHART_STATUS_NAME]
      --,[VIS_NEW_TO_SYS_YN]
      --,[VIS_NEW_TO_DEP_YN]
      --,[VIS_NEW_TO_PROV_YN]
      --,[APPT_SERIAL_NUM]
      --,[RESCHED_APPT_CSN_ID]
      ,[PRC_ID]
      ,[PRC_NAME]
      --,[APPT_BLOCK_C]
      --,[APPT_BLOCK_NAME]
      --,[APPT_LENGTH]
      --,[APPT_STATUS_C]
      ,[APPT_STATUS_NAME]
      --,[APPT_CONF_STAT_C]
      --,[CANCEL_LEAD_HOURS]
      --,[CANCEL_INITIATOR]
      --,[COMPLETED_STATUS_YN]
      --,[SAME_DAY_YN]
      --,[SAME_DAY_CANC_YN]
      --,[CANCEL_REASON_C]
      --,[CANCEL_REASON_NAME]
      --,[WALK_IN_YN]
      --,[OVERBOOKED_YN]
      --,[OVERRIDE_YN]
      --,[UNAVAILABLE_TIME_YN]
      --,[CHANGE_CNT]
      --,[JOINT_APPT_YN]
      --,[PHONE_REM_STAT_C]
      --,[PHONE_REM_STAT_NAME]
      --,[CONTACT_DATE]
      ,[APPT_MADE_DATE]
      --,[APPT_CANC_DATE]
      --,[APPT_CONF_DTTM]
      ,[APPT_DTTM]
      --,[SIGNIN_DTTM]
      --,[PAGED_DTTM]
      --,[BEGIN_CHECKIN_DTTM]
      --,[CHECKIN_DTTM]
      --,[ARVL_LIST_REMOVE_DTTM]
      --,[ROOMED_DTTM]
      --,[FIRST_ROOM_ASSIGN_DTTM]
      --,[NURSE_LEAVE_DTTM]
      --,[PHYS_ENTER_DTTM]
      --,[VISIT_END_DTTM]
      --,[CHECKOUT_DTTM]
      --,[TIME_TO_ROOM_MINUTES]
      --,[TIME_IN_ROOM_MINUTES]
      --,[CYCLE_TIME_MINUTES]
      ,[REFERRING_PROV_ID]
      ,[REFERRING_PROV_NAME_WID]
      ,appt.[PROV_ID]
      ,[PROV_NAME_WID]
      --,[RPT_GRP_FIVE]
      --,[APPT_ENTRY_USER_ID]
      --,[APPT_ENTRY_USER_NAME_WID]
      ,[PROV_NAME]
		--,SER2.PROV_ID AS admPROV_ID
		--,SER2.Prov_Nme AS admProv_Nme
		,SER3.PROV_ID AS ATN_PROV_ID
		,SER3.Prov_Nme AS ATN_PROV_NAME
      --,[PAYOR_ID]
      --,[PAYOR_NAME]
      --,[BENEFIT_PLAN_ID]
      --,[BENEFIT_PLAN_NAME]
      --,[FIN_CLASS_NAME]
      --,[DO_NOT_BILL_INS_YN]
      --,[SELF_PAY_VISIT_YN]
      ,[HSP_ACCOUNT_ID]
      ,[ACCOUNT_ID]
      --,[COPAY_DUE]
      --,[COPAY_COLLECTED]
      --,[COPAY_USER_ID]
      --,[COPAY_USER_NAME_WID]
      ,[DEPARTMENT_ID]
      ,[DEPARTMENT_NAME]
      ,[DEPT_ABBREVIATION]
      --,[RPT_GRP_THIRTY]
      --,[RPT_GRP_SIX]
      --,[RPT_GRP_SEVEN]
      --,[DEPT_SPECIALTY_C]
      ,[DEPT_SPECIALTY_NAME]
      --,[CENTER_C]
      --,[CENTER_NAME]
      --,[LOC_ID]
      --,[LOC_NAME]
      --,[SERV_AREA_ID]
      --,[APPT_STATUS_FLAG]
      --,[Load_Dtm]
      --,[sk_Dim_Pt]
      --,[sk_Fact_Pt_Enc_Clrt]
      --,[sk_Fact_Pt_Acct]
      --,[VIS_NEW_TO_SPEC_YN]
      --,[VIS_NEW_TO_SERV_AREA_YN]
      --,[VIS_NEW_TO_LOC_YN]
      ,[REFERRAL_ID]
      ,[ENTRY_DATE]
      ,[RFL_STATUS_NAME]
      ,[RFL_TYPE_NAME]
      --,[PROV_SPECIALTY_C]
      --,[PROV_SPECIALTY_NAME]
      --,[ENC_TYPE_C]
      ,[ENC_TYPE_TITLE]
      --,[APPT_CONF_STAT_NAME]
      --,[ZIP]
      --,[SER_RPT_GRP_SIX]
      --,[SER_RPT_GRP_EIGHT]
      --,[F2F_Flag]
      --,[APPT_CANC_DTTM]
      --,[APPT_CANC_USER_ID]
      --,[APPT_CANC_USER_NAME_WID]
      --,[APPT_CONF_USER_ID]
      --,[APPT_CONF_USER_NAME]
      --,[CHANGE_DATE]
      ,[APPT_MADE_DTTM]
      --,[UPDATE_DATE]
      --,[BILL_PROV_YN]
      ,[PROV_TYPE_OT_NAME]
      --,[PAT_SCHED_MYC_STAT_C]
      --,[PAT_SCHED_MYC_STAT_NAME]
      --,[ALLOWED_TELEHEALTH_MODES]
      --,[AUDIT_TASK]
      --,[AUDIT_ACTION]
      --,[AUDIT_TYPE]
  FROM [DS_HSDM_App].[Stage].[Scheduled_Appointment] appt
  LEFT OUTER JOIN (SELECT PAT_ENC_CSN_ID
                        , sk_Dim_Clrt_SERsrc
						, sk_Dim_Physcn
						, ROW_NUMBER() OVER (PARTITION BY sk_Fact_Pt_Enc_Clrt ORDER BY Atn_Beg_Dtm, CASE
																									  WHEN Atn_End_Dtm = '1900-01-01' THEN GETDATE()
																									  ELSE Atn_End_Dtm
																									END) AS 'Atn_Seq'
				   FROM DS_HSDW_Prod.Rptg.vwFact_Pt_Enc_Atn_Prov_All) AS admatn ON (admatn.PAT_ENC_CSN_ID = appt.PAT_ENC_CSN_ID) AND admatn.Atn_Seq = 1
LEFT JOIN DS_HSDW_Prod.Rptg.vwDim_Clrt_SERsrc		AS  SER2		ON SER2.sk_Dim_Clrt_SERsrc=admatn.sk_Dim_Clrt_SERsrc
  LEFT OUTER JOIN (SELECT PAT_ENC_CSN_ID
                        , sk_Dim_Clrt_SERsrc
						, sk_Dim_Physcn
						, ROW_NUMBER() OVER (PARTITION BY sk_Fact_Pt_Enc_Clrt ORDER BY Atn_Beg_Dtm DESC, CASE
																										   WHEN Atn_End_Dtm = '1900-01-01' THEN GETDATE()
																										   ELSE Atn_End_Dtm
																									     END DESC) AS 'Atn_Seq'
				   FROM DS_HSDW_Prod.Rptg.vwFact_Pt_Enc_Atn_Prov_All) AS dschatn ON (dschatn.PAT_ENC_CSN_ID = appt.PAT_ENC_CSN_ID) AND dschatn.Atn_Seq = 1
LEFT JOIN DS_HSDW_Prod.Rptg.vwDim_Clrt_SERsrc		AS  SER3		ON SER3.sk_Dim_Clrt_SERsrc=dschatn.sk_Dim_Clrt_SERsrc
  WHERE DEPARTMENT_ID = 10243134
  AND APPT_DT > '6/13/2022 00:00:00'
  AND APPT_STATUS_NAME <> 'Canceled'
  ORDER BY APPT_DT